/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import controllers.CriarEventoCientificoAprtirDeFicheiroController;
import controllers.CriarEventoCientificoController;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Empresa;

/**
 *
 * @author RXFB73
 */
public class CriarEventoCientificoApartirDeFicheiro extends javax.swing.JDialog {

    private CriarEventoCientificoController m_controllerCEC;
    /**
     * Creates new form CriarEventoCientíficoManual
     * @param parent
     * @param modal
     * @param empresa
     */
    public CriarEventoCientificoApartirDeFicheiro(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        m_controllerCEC = new CriarEventoCientificoController(empresa);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        txt_ano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_host = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_country = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCheckData = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Subm = new javax.swing.JTextField();
        txt_Rev = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_regist = new javax.swing.JTextField();
        txt_artg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_dataFim = new javax.swing.JTextField();
        txt_dataIni = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_site = new javax.swing.JTextField();
        BtnLoad = new javax.swing.JButton();
        txtFich = new javax.swing.JTextField();
        ComboEventos = new javax.swing.JComboBox();
        ComboOrg = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        btnDelOrg = new javax.swing.JButton();
        btnNewOrg = new javax.swing.JButton();
        btnEditOrg = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Título:");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("UC12 - Criar Evento Científico a partir de Ficheiro");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Ano:");

        txt_ano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ano.setForeground(new java.awt.Color(153, 153, 153));
        txt_ano.setText("insira ano");
        txt_ano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_anoMouseClicked(evt);
            }
        });
        txt_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Evento:");

        txt_host.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_host.setForeground(new java.awt.Color(153, 153, 153));
        txt_host.setText("insira anfitrião");
        txt_host.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_hostMouseClicked(evt);
            }
        });
        txt_host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hostActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Insira anfitrião:");

        txt_city.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_city.setForeground(new java.awt.Color(153, 153, 153));
        txt_city.setText("insira cidade");
        txt_city.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cityMouseClicked(evt);
            }
        });
        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Cidade:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("País:");

        txt_country.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_country.setForeground(new java.awt.Color(153, 153, 153));
        txt_country.setText("insira País");
        txt_country.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_countryMouseClicked(evt);
            }
        });
        txt_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_countryActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCheckData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCheckData.setText("Confirmar dados");
        btnCheckData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckDataActionPerformed(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setForeground(new java.awt.Color(153, 153, 153));
        txt_id.setText("insira ID");
        txt_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_idMouseClicked(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Limite Revisão:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Limite de Submissão:");

        txt_Subm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Subm.setForeground(new java.awt.Color(153, 153, 153));
        txt_Subm.setText("insira limite submissão");
        txt_Subm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_SubmMouseClicked(evt);
            }
        });
        txt_Subm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SubmActionPerformed(evt);
            }
        });

        txt_Rev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Rev.setForeground(new java.awt.Color(153, 153, 153));
        txt_Rev.setText("insira limite revisão");
        txt_Rev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_RevMouseClicked(evt);
            }
        });
        txt_Rev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RevActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Limite Registo:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Limite Entrega Artigo:");

        txt_regist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_regist.setForeground(new java.awt.Color(153, 153, 153));
        txt_regist.setText("insira registo");
        txt_regist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_registMouseClicked(evt);
            }
        });
        txt_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registActionPerformed(evt);
            }
        });

        txt_artg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_artg.setForeground(new java.awt.Color(153, 153, 153));
        txt_artg.setText("insira entrega artigo");
        txt_artg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_artgMouseClicked(evt);
            }
        });
        txt_artg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_artgActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Data Fim:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Data Inicio:");

        txt_dataFim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_dataFim.setForeground(new java.awt.Color(153, 153, 153));
        txt_dataFim.setText("insira data fim");
        txt_dataFim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dataFimMouseClicked(evt);
            }
        });
        txt_dataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataFimActionPerformed(evt);
            }
        });

        txt_dataIni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_dataIni.setForeground(new java.awt.Color(153, 153, 153));
        txt_dataIni.setText("insira data inicio");
        txt_dataIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dataIniMouseClicked(evt);
            }
        });
        txt_dataIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataIniActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("Website:");

        txt_site.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_site.setForeground(new java.awt.Color(153, 153, 153));
        txt_site.setText("insira website");
        txt_site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_siteMouseClicked(evt);
            }
        });
        txt_site.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_siteActionPerformed(evt);
            }
        });

        BtnLoad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnLoad.setText("Carregar dados");
        BtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoadActionPerformed(evt);
            }
        });

        txtFich.setForeground(new java.awt.Color(153, 153, 153));
        txtFich.setText("nenhum ficheiro seleccionado");

        ComboEventos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEventosActionPerformed(evt);
            }
        });

        ComboOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setText("Organizadores:");

        btnDelOrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelOrg.setText("Apagar Organizador");
        btnDelOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelOrgActionPerformed(evt);
            }
        });

        btnNewOrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewOrg.setText("Novo Organizador");
        btnNewOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrgActionPerformed(evt);
            }
        });

        btnEditOrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditOrg.setText("Editar Organizador");
        btnEditOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_city, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_country, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Subm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Rev)
                            .addComponent(txt_host, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ano)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dataIni)
                            .addComponent(txt_artg)
                            .addComponent(txt_regist)
                            .addComponent(txt_dataFim)
                            .addComponent(txt_site, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboEventos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFich)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNewOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCheckData, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtFich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboEventos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Subm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Rev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_artg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_regist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_site, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelOrg)
                    .addComponent(btnNewOrg)
                    .addComponent(btnEditOrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataFimActionPerformed

    private void txt_dataFimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dataFimMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataFimMouseClicked

    private void txt_artgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_artgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_artgActionPerformed

    private void txt_artgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_artgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_artgMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idMouseClicked

    private void txt_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registActionPerformed

    private void txt_registMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registMouseClicked

    private void btnCheckDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckDataActionPerformed
        // TODO add your handling code here:
        run();
        JOptionPane.showMessageDialog(null, "evento criado com sucesso!");
    }//GEN-LAST:event_btnCheckDataActionPerformed

    private void txt_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_countryActionPerformed

    private void txt_countryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_countryMouseClicked
        // TODO add your handling code here:
        txt_country.setText("");
    }//GEN-LAST:event_txt_countryMouseClicked

    private void txt_SubmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SubmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SubmActionPerformed

    private void txt_SubmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_SubmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SubmMouseClicked

    private void txt_RevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RevActionPerformed

    private void txt_RevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_RevMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RevMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void BtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoadActionPerformed
        try {
            JFileChooser fich = new JFileChooser();
            int resp = fich.showOpenDialog(fich);
            File f = null;
            if (resp == JFileChooser.APPROVE_OPTION) {
                f = fich.getSelectedFile();
            }
            CriarEventoCientificoAprtirDeFicheiroController.TrataCarregar(f);
            txtFich.setText(f.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o ficheiro!");
        }
    }//GEN-LAST:event_BtnLoadActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_cityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cityMouseClicked
        // TODO add your handling code here:
        txt_city.setText("");
    }//GEN-LAST:event_txt_cityMouseClicked

    private void txt_hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hostActionPerformed

    private void txt_hostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_hostMouseClicked
        // TODO add your handling code here:
        txt_host.setText("");
    }//GEN-LAST:event_txt_hostMouseClicked

    private void txt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anoActionPerformed

    private void txt_anoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_anoMouseClicked
        // TODO add your handling code here:
        txt_ano.setText("");
    }//GEN-LAST:event_txt_anoMouseClicked

    private void btnNewOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewOrgActionPerformed

    private void btnDelOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelOrgActionPerformed

    private void txt_dataIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataIniActionPerformed

    private void txt_dataIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dataIniMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataIniMouseClicked

    private void txt_siteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_siteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_siteActionPerformed

    private void txt_siteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_siteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_siteMouseClicked

    private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseWheelMoved

    private void btnEditOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditOrgActionPerformed

    private void ComboEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEventosActionPerformed
         ComboEventos = new JComboBox(CriarEventoCientificoAprtirDeFicheiroController.data.toArray());

        if(CriarEventoCientificoAprtirDeFicheiroController.data.isEmpty()){
            ComboEventos.setEnabled(false);
            ComboOrg.setEnabled(false);
            txtFich.setEnabled(false);
            jTextField2.setEnabled(false);
            txt_country.setEnabled(false);
            txt_Rev.setEnabled(false);
            txt_regist.setEnabled(false);
            txt_dataFim.setEnabled(false);
            txt_site.setEnabled(false);
            txt_city.setEnabled(false);
            txt_Subm.setEnabled(false);
            txt_artg.setEnabled(false);
            txt_dataIni.setEnabled(false);
            txt_host.setEnabled(false);
            txt_id.setEnabled(false);
            txt_ano.setEnabled(false);
            
        } else {
            ComboEventos.setEnabled(true);
            ComboOrg.setEnabled(true);
            txtFich.setEnabled(true);
            jTextField2.setEnabled(true);
            txt_country.setEnabled(true);
            txt_Rev.setEnabled(true);
            txt_regist.setEnabled(true);
            txt_dataFim.setEnabled(true);
            txt_site.setEnabled(true);
            txt_city.setEnabled(true);
            txt_Subm.setEnabled(true);
            txt_artg.setEnabled(true);
            txt_dataIni.setEnabled(true);
            txt_host.setEnabled(true);
            txt_id.setEnabled(true);
            txt_ano.setEnabled(true);
            
             for (Object data : CriarEventoCientificoAprtirDeFicheiroController.data) {
                 ComboEventos.addItem(data);
             }
             /*  for (int i = 0; i < lista_utilizadores.size(); i++) {
             if (!(lista_utilizadores.get(i)).equals(lista_utilizadores.get(select))) {
             jComboBox_org_adicionar.addItem(lista_utilizadores.get(i).getNome());
             }
             }   */         
        }
    }//GEN-LAST:event_ComboEventosActionPerformed

    public CriarEventoCientificoController getM_controllerCEC() {
        return m_controllerCEC;
    }

    public void setM_controllerCEC(CriarEventoCientificoController m_controllerCEC) {
        this.m_controllerCEC = m_controllerCEC;
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoad;
    private javax.swing.JComboBox ComboEventos;
    private javax.swing.JComboBox ComboOrg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCheckData;
    private javax.swing.JButton btnDelOrg;
    private javax.swing.JButton btnEditOrg;
    private javax.swing.JButton btnNewOrg;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private javax.swing.JTextField txtFich;
    private javax.swing.JTextField txt_Rev;
    private javax.swing.JTextField txt_Subm;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_artg;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_country;
    private javax.swing.JTextField txt_dataFim;
    private javax.swing.JTextField txt_dataIni;
    private javax.swing.JTextField txt_host;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_regist;
    private javax.swing.JTextField txt_site;
    // End of variables declaration//GEN-END:variables
    public void run() {
        novoEvento();

        introduzTitulo();
      /*  introduzDescricao();
        introduzLocal();
        introduzDataInicio();
        introduzDataFim();
        introduzDataLimiteSubmissão();*/
        adicionaOrganizadores();
    }

    private void adicionaOrganizadores() {

    }

    private void novoEvento() {
        m_controllerCEC.novoEvento();
    }

    private void introduzTitulo() {
        String strTitulo = this.txt_ano.getText();

        m_controllerCEC.setTitulo(strTitulo);
    }
/*
    private void introduzDescricao() {
        String strDescricao = this.txt_texto.getText();

        m_controllerCEC.setDescricao(strDescricao);
    }

    private void introduzLocal() {
        String strLocal = this.txt_usernameEmailUtilizador.getText();

        m_controllerCEC.setLocal(strLocal);
    }

    private void introduzDataInicio() {
        String strDataInicio = this.txt_host.getText();

        m_controllerCEC.setDataInicio(strDataInicio);
    }

    private void introduzDataFim() {
        String strDataFim = this.txt_city.getText();

        m_controllerCEC.setDataFim(strDataFim);
    }

    private void introduzDataLimiteSubmissão() {
        String strDataLimiteSubmissão = this.txt_country.getText();

        m_controllerCEC.setDataLimiteSubmissão(strDataLimiteSubmissão);
    }

    public String[] obterArrayOrganizadores() {
        String[] items = new String[m_controllerCEC.getM_evento().getListaOrganizadores().size()];

        int numeroOrganizadores = 0;
        for (int i = numeroOrganizadores; i < items.length; i++) {
            {
                items[i] = m_controllerCEC.getM_evento().getListaOrganizadores().get(i).getNome();
                numeroOrganizadores++;
            }
        }
        return items;
    }

    public void trataJlist() {
        this.lista_organizadores.removeAll();

        lista_organizadores = new JList(obterArrayOrganizadores());
        jScrollPane2.setViewportView(lista_organizadores);
    }*/
}
